name: PR Reviewer Agent

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

  issue_comment:
    types: [created]

jobs:
  pr_agent_job:
    if: >
      github.event.sender.type != 'Bot' &&
      (
        github.event_name == 'pull_request' ||
        github.event.issue.pull_request != null
      )

    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write
      contents: write

    steps:
      - name: Run PR Agent
        uses: the-pr-agent/pr-agent@main
        env:
          config.model: "gemini/gemini-1.5-flash"
          config.fallback_models: '["gemini/gemini-1.5-flash"]'

          CUSTOM_LLM_PROVIDER: "gemini"
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          github_action_config.auto_review: "true"
          github_action_config.auto_describe: "true"
          github_action_config.pr_commands: "true"